name: Restrict PR to main

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    name: Check Source Branch
    runs-on: ubuntu-latest

    steps:
      - name: Validate source branch
        run: |
          if [[ ! "${{ github.head_ref }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Pull requests to 'main' are only allowed from branches matching the pattern 'v*.*.*'."
            exit 1
          fi
