name: Restrict PR to main

on:
  pull_request:  # Trigger this workflow only on pull requests
    branches:
      - main  # This ensures the workflow triggers only when the target branch is 'main'

jobs:
  check-source-branch:
    if: github.base_ref == 'main'  # Run this job ONLY if the target branch is 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Validate source branch
        run: |
          if [[ ! "${{ github.head_ref }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Pull requests to 'main' are only allowed from branches matching the pattern 'v*.*.*'."
            exit 1
          fi
